version: '3'

services:
  todolist:
    build: ./backend
    image: r3dkar/todolist
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema-public
    volumes:
      - ./frontend/dist:/app/dist/frontend
    ports:
      - 80:${SERVER_PORT}
    networks:
      - backend
    depends_on:
     - db

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
